Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,18 +21,22 @@ jobs:
         AWS_USER: ${{ secrets.AWS_USER }}
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: |
+        # Save the private key to a file
         echo "$SSH_PRIVATE_KEY" > private_key.pem
         chmod 600 private_key.pem
 
-        # SSH into the instance and update the server
+        # Add the EC2 instance to known hosts
+        ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts
+
+        # SSH into the instance and execute deployment commands
         ssh -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
+          set -e # Exit on any error
           cd /home/ubuntu/Moodify-server
           git pull origin main
-          npm install
+          npm install --production
           npm run migrations
           pm2 restart all
         EOF
 
-
-        # Clean up
+        # Clean up the private key
         rm -f private_key.pem
